# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/scary__/LoR Simulator/LoRDeckpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/scary__/LoR Simulator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/scary__/LoR Simulator/CMakeFiles" "/home/scary__/LoR Simulator/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/scary__/LoR Simulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DeckTest

# Build rule for target.
DeckTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DeckTest
.PHONY : DeckTest

# fast build rule for target.
DeckTest/fast:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/build
.PHONY : DeckTest/fast

#=============================================================================
# Target rules for targets named LoRDeck++

# Build rule for target.
LoRDeck++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LoRDeck++
.PHONY : LoRDeck++

# fast build rule for target.
LoRDeck++/fast:
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/build
.PHONY : LoRDeck++/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/LoRCard.o: src/LoRCard.cpp.o

.PHONY : src/LoRCard.o

# target to build an object file
src/LoRCard.cpp.o:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRCard.cpp.o
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRCard.cpp.o
.PHONY : src/LoRCard.cpp.o

src/LoRCard.i: src/LoRCard.cpp.i

.PHONY : src/LoRCard.i

# target to preprocess a source file
src/LoRCard.cpp.i:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRCard.cpp.i
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRCard.cpp.i
.PHONY : src/LoRCard.cpp.i

src/LoRCard.s: src/LoRCard.cpp.s

.PHONY : src/LoRCard.s

# target to generate assembly for a file
src/LoRCard.cpp.s:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRCard.cpp.s
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRCard.cpp.s
.PHONY : src/LoRCard.cpp.s

src/LoRDeck.o: src/LoRDeck.cpp.o

.PHONY : src/LoRDeck.o

# target to build an object file
src/LoRDeck.cpp.o:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRDeck.cpp.o
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRDeck.cpp.o
.PHONY : src/LoRDeck.cpp.o

src/LoRDeck.i: src/LoRDeck.cpp.i

.PHONY : src/LoRDeck.i

# target to preprocess a source file
src/LoRDeck.cpp.i:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRDeck.cpp.i
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRDeck.cpp.i
.PHONY : src/LoRDeck.cpp.i

src/LoRDeck.s: src/LoRDeck.cpp.s

.PHONY : src/LoRDeck.s

# target to generate assembly for a file
src/LoRDeck.cpp.s:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/LoRDeck.cpp.s
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/LoRDeck.cpp.s
.PHONY : src/LoRDeck.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/utils.cpp.o
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/utils.cpp.i
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/src/utils.cpp.s
	$(MAKE) -f CMakeFiles/LoRDeck++.dir/build.make CMakeFiles/LoRDeck++.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/main.o: tests/main.cpp.o

.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i

.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s

.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) -f CMakeFiles/DeckTest.dir/build.make CMakeFiles/DeckTest.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DeckTest"
	@echo "... LoRDeck++"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/LoRCard.o"
	@echo "... src/LoRCard.i"
	@echo "... src/LoRCard.s"
	@echo "... src/LoRDeck.o"
	@echo "... src/LoRDeck.i"
	@echo "... src/LoRDeck.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

